<a href="https://colab.research.google.com/github/chemkemeimyers/PythonProjects/blob/main/SavingNLoadingFiles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
path = '/content/drive/MyDrive/MachineLearningCourse/Python/StockData.csv'
data=pd.read_csv(path)

In [3]:
data.head()

  stock        date    price
0  AAPL  08-02-2013  67.8542
1  AAPL  11-02-2013  68.5614
2  AAPL  12-02-2013  66.8428
3  AAPL  13-02-2013  66.7156
4  AAPL  14-02-2013  66.6556

In [4]:
path_excel = '/content/drive/MyDrive/MachineLearningCourse/Python/StockData.xlsx'
data_excel = pd.read_excel(path_excel)

In [5]:
data_excel.head()

  stock       date    price
0  AAPL 2013-02-08  67.8542
1  AAPL 2013-02-11  68.5614
2  AAPL 2013-02-12  66.8428
3  AAPL 2013-02-13  66.7156
4  AAPL 2013-02-14  66.6556

In [6]:
data.to_csv('/content/drive/MyDrive/MachineLearningCourse/Python/Saved_StockData.csv', index=False)

In [7]:
data.to_excel('/content/drive/MyDrive/MachineLearningCourse/Python/Saved_StockData.xlsx')

In [8]:
#Pandas
data.head(10)

  stock        date    price
0  AAPL  08-02-2013  67.8542
1  AAPL  11-02-2013  68.5614
2  AAPL  12-02-2013  66.8428
3  AAPL  13-02-2013  66.7156
4  AAPL  14-02-2013  66.6556
5  AAPL  15-02-2013  65.7371
6  AAPL  19-02-2013  65.7128
7  AAPL  20-02-2013  64.1214
8  AAPL  21-02-2013  63.7228
9  AAPL  22-02-2013  64.4014

In [9]:
data.tail(10)

     stock        date  price
5026   ZTS  25-01-2018  79.25
5027   ZTS  26-01-2018  80.09
5028   ZTS  29-01-2018  79.18
5029   ZTS  30-01-2018  78.35
5030   ZTS  31-01-2018  76.73
5031   ZTS  01-02-2018  77.82
5032   ZTS  02-02-2018  76.78
5033   ZTS  05-02-2018  73.83
5034   ZTS  06-02-2018  73.27
5035   ZTS  07-02-2018  73.86

In [10]:
data.shape

(5036, 3)

In [11]:
data.describe()

             price
count  5036.000000
mean     73.057030
std      29.011126
min      28.400000
25%      54.067500
50%      69.085000
75%      79.250000
max     179.260000

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   stock   5036 non-null   object
 1   date    5036 non-null   object
 2   price   5036 non-null   float64
dtypes: float64(1), object(2)
memory usage: 118.2+ KB

In [13]:
data["stock"].unique()

array(['AAPL', 'SNI', 'TJX', 'ZTS'], dtype=object)

In [14]:
data["stock"].value_counts()

stock
AAPL    1259
SNI     1259
TJX     1259
ZTS     1259
Name: count, dtype: int64

In [15]:
data["stock"].value_counts(normalize=True)

stock
AAPL    0.25
SNI     0.25
TJX     0.25
ZTS     0.25
Name: proportion, dtype: float64

In [16]:
data["stock"].min()

'AAPL'

In [17]:
data["price"].min()

28.4

In [18]:
data["price"].max()

179.26

In [19]:
data["price"].mean()

np.float64(73.05702966640192)

In [20]:
data["price"].median()

69.08500000000001

In [21]:
data["stock"].mode()

0    AAPL
1     SNI
2     TJX
3     ZTS
Name: stock, dtype: object

In [22]:
data["price"].mode()[0]

np.float64(74.59)

In [23]:
data.describe()

             price
count  5036.000000
mean     73.057030
std      29.011126
min      28.400000
25%      54.067500
50%      69.085000
75%      79.250000
max     179.260000

In [24]:
dt = {'A':[1, 2, 3, 4, 5], 'B':[6, 7, 8, 9, 10]}
df = pd.DataFrame(dt)
df['A'].mean()

np.float64(3.0)

In [25]:
dt = {'A':[1, 2, 3, 4, 5], 'B':[6, 7, 8, 9, 10]}
df = pd.DataFrame(dt)
df['B'].median()

8.0

In [26]:
data.groupby(["stock"])["price"].mean()

stock
AAPL    109.066698
SNI      71.319206
TJX      66.743566
ZTS      45.098648
Name: price, dtype: float64

In [27]:
data.groupby(["stock"])["price"].median()

stock
AAPL    109.01
SNI      72.31
TJX      68.85
ZTS      45.62
Name: price, dtype: float64

In [28]:
#define a function to increase price of a stock by 10%
def profit(s):
  return s + s * 0.1

In [29]:
data['price'].apply(profit)

0       74.63962
1       75.41754
2       73.52708
3       73.38716
4       73.32116
          ...
5031    85.60200
5032    84.45800
5033    81.21300
5034    80.59700
5035    81.24600
Name: price, Length: 5036, dtype: float64

In [30]:
data['New_Price'] = data['price'].apply(profit)

In [31]:
data.head()

  stock        date    price  New_Price
0  AAPL  08-02-2013  67.8542   74.63962
1  AAPL  11-02-2013  68.5614   75.41754
2  AAPL  12-02-2013  66.8428   73.52708
3  AAPL  13-02-2013  66.7156   73.38716
4  AAPL  14-02-2013  66.6556   73.32116

In [32]:
data.sort_values(by='New_Price', ascending=False)

     stock        date   price  New_Price
1244  AAPL  18-01-2018  179.26    197.186
1243  AAPL  17-01-2018  179.10    197.010
1245  AAPL  19-01-2018  178.46    196.306
1241  AAPL  12-01-2018  177.09    194.799
1247  AAPL  23-01-2018  177.04    194.744
...    ...         ...     ...        ...
4076   ZTS  17-04-2014   28.60     31.460
4074   ZTS  15-04-2014   28.55     31.405
4075   ZTS  16-04-2014   28.53     31.383
4073   ZTS  14-04-2014   28.48     31.328
4072   ZTS  11-04-2014   28.40     31.240

[5036 rows x 4 columns]

In [33]:
data.head()

  stock        date    price  New_Price
0  AAPL  08-02-2013  67.8542   74.63962
1  AAPL  11-02-2013  68.5614   75.41754
2  AAPL  12-02-2013  66.8428   73.52708
3  AAPL  13-02-2013  66.7156   73.38716
4  AAPL  14-02-2013  66.6556   73.32116

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   stock      5036 non-null   object
 1   date       5036 non-null   object
 2   price      5036 non-null   float64
 3   New_Price  5036 non-null   float64
dtypes: float64(2), object(2)
memory usage: 157.5+ KB

In [35]:
data['date'] = pd.to_datetime(data['date'], dayfirst=True)

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   stock      5036 non-null   object
 1   date       5036 non-null   datetime64[ns]
 2   price      5036 non-null   float64
 3   New_Price  5036 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 157.5+ KB

In [37]:
data.head()

  stock       date    price  New_Price
0  AAPL 2013-02-08  67.8542   74.63962
1  AAPL 2013-02-11  68.5614   75.41754
2  AAPL 2013-02-12  66.8428   73.52708
3  AAPL 2013-02-13  66.7156   73.38716
4  AAPL 2013-02-14  66.6556   73.32116

In [39]:
data['date'].dt.strftime('%m/%d/%Y')

0       02/08/2013
1       02/11/2013
2       02/12/2013
3       02/13/2013
4       02/14/2013
           ...
5031    02/01/2018
5032    02/02/2018
5033    02/05/2018
5034    02/06/2018
5035    02/07/2018
Name: date, Length: 5036, dtype: object

In [40]:
data['date'].dt.year

0       2013
1       2013
2       2013
3       2013
4       2013
        ...
5031    2018
5032    2018
5033    2018
5034    2018
5035    2018
Name: date, Length: 5036, dtype: int32

In [41]:
data['date'].dt.month

0       2
1       2
2       2
3       2
4       2
       ..
5031    2
5032    2
5033    2
5034    2
5035    2
Name: date, Length: 5036, dtype: int32

In [42]:
data['year'] = data['date'].dt.year

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   stock      5036 non-null   object
 1   date       5036 non-null   datetime64[ns]
 2   price      5036 non-null   float64
 3   New_Price  5036 non-null   float64
 4   year       5036 non-null   int32
dtypes: datetime64[ns](1), float64(2), int32(1), object(1)
memory usage: 177.2+ KB

In [44]:
data.head()

  stock       date    price  New_Price  year
0  AAPL 2013-02-08  67.8542   74.63962  2013
1  AAPL 2013-02-11  68.5614   75.41754  2013
2  AAPL 2013-02-12  66.8428   73.52708  2013
3  AAPL 2013-02-13  66.7156   73.38716  2013
4  AAPL 2013-02-14  66.6556   73.32116  2013

In [45]:
data['month'] = data['date'].dt.month

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   stock      5036 non-null   object
 1   date       5036 non-null   datetime64[ns]
 2   price      5036 non-null   float64
 3   New_Price  5036 non-null   float64
 4   year       5036 non-null   int32
 5   month      5036 non-null   int32
dtypes: datetime64[ns](1), float64(2), int32(2), object(1)
memory usage: 196.8+ KB